# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Image_Scrapper.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(371, 411)
        self.download = QtWidgets.QPushButton(Dialog)
        self.download.setGeometry(QtCore.QRect(10, 310, 351, 31))
        self.download.setObjectName("download")
        self.engine_box = QtWidgets.QGroupBox(Dialog)
        self.engine_box.setGeometry(QtCore.QRect(10, 10, 91, 161))
        self.engine_box.setObjectName("engine_box")
        self.google = QtWidgets.QRadioButton(self.engine_box)
        self.google.setGeometry(QtCore.QRect(10, 20, 90, 16))
        self.google.setObjectName("google")
        self.naver = QtWidgets.QRadioButton(self.engine_box)
        self.naver.setGeometry(QtCore.QRect(10, 40, 90, 16))
        self.naver.setObjectName("naver")
        self.bing = QtWidgets.QRadioButton(self.engine_box)
        self.bing.setGeometry(QtCore.QRect(10, 60, 90, 16))
        self.bing.setObjectName("bing")
        self.github = QtWidgets.QPushButton(self.engine_box)
        self.github.setGeometry(QtCore.QRect(0, 120, 91, 41))
        self.github.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.github.setText("")
        self.github.setObjectName("github")
        self.google_copyright = QtWidgets.QGroupBox(Dialog)
        self.google_copyright.setGeometry(QtCore.QRect(110, 10, 250, 161))
        self.google_copyright.setObjectName("google_copyright")
        self.google_0 = QtWidgets.QRadioButton(self.google_copyright)
        self.google_0.setGeometry(QtCore.QRect(10, 20, 241, 16))
        self.google_0.setObjectName("google_0")
        self.google_1 = QtWidgets.QRadioButton(self.google_copyright)
        self.google_1.setGeometry(QtCore.QRect(10, 40, 241, 16))
        self.google_1.setObjectName("google_1")
        self.google_2 = QtWidgets.QRadioButton(self.google_copyright)
        self.google_2.setGeometry(QtCore.QRect(10, 60, 241, 16))
        self.google_2.setObjectName("google_2")
        self.google_3 = QtWidgets.QRadioButton(self.google_copyright)
        self.google_3.setGeometry(QtCore.QRect(10, 80, 241, 16))
        self.google_3.setObjectName("google_3")
        self.google_4 = QtWidgets.QRadioButton(self.google_copyright)
        self.google_4.setGeometry(QtCore.QRect(10, 100, 241, 16))
        self.google_4.setObjectName("google_4")
        self.select_folder = QtWidgets.QPushButton(Dialog)
        self.select_folder.setGeometry(QtCore.QRect(290, 230, 71, 41))
        self.select_folder.setObjectName("select_folder")
        self.directory_path = QtWidgets.QTextBrowser(Dialog)
        self.directory_path.setGeometry(QtCore.QRect(10, 230, 271, 41))
        self.directory_path.setObjectName("directory_path")
        self.cnt = QtWidgets.QSpinBox(Dialog)
        self.cnt.setGeometry(QtCore.QRect(290, 280, 70, 21))
        self.cnt.setMinimum(1)
        self.cnt.setMaximum(1000)
        self.cnt.setObjectName("cnt")
        self.search = QtWidgets.QLineEdit(Dialog)
        self.search.setGeometry(QtCore.QRect(10, 280, 271, 21))
        self.search.setObjectName("search")
        self.driver_path = QtWidgets.QTextBrowser(Dialog)
        self.driver_path.setGeometry(QtCore.QRect(10, 180, 271, 41))
        self.driver_path.setObjectName("driver_path")
        self.select_driver = QtWidgets.QPushButton(Dialog)
        self.select_driver.setGeometry(QtCore.QRect(290, 180, 71, 41))
        self.select_driver.setObjectName("select_driver")
        self.bing_copyright = QtWidgets.QGroupBox(Dialog)
        self.bing_copyright.setGeometry(QtCore.QRect(110, 10, 250, 161))
        self.bing_copyright.setObjectName("bing_copyright")
        self.bing_1 = QtWidgets.QRadioButton(self.bing_copyright)
        self.bing_1.setGeometry(QtCore.QRect(10, 40, 241, 16))
        self.bing_1.setObjectName("bing_1")
        self.bing_2 = QtWidgets.QRadioButton(self.bing_copyright)
        self.bing_2.setGeometry(QtCore.QRect(10, 60, 241, 16))
        self.bing_2.setObjectName("bing_2")
        self.bing_3 = QtWidgets.QRadioButton(self.bing_copyright)
        self.bing_3.setGeometry(QtCore.QRect(10, 80, 241, 16))
        self.bing_3.setObjectName("bing_3")
        self.bing_4 = QtWidgets.QRadioButton(self.bing_copyright)
        self.bing_4.setGeometry(QtCore.QRect(10, 100, 241, 16))
        self.bing_4.setObjectName("bing_4")
        self.bing_5 = QtWidgets.QRadioButton(self.bing_copyright)
        self.bing_5.setGeometry(QtCore.QRect(10, 120, 241, 16))
        self.bing_5.setObjectName("bing_5")
        self.bing_6 = QtWidgets.QRadioButton(self.bing_copyright)
        self.bing_6.setGeometry(QtCore.QRect(10, 140, 241, 16))
        self.bing_6.setObjectName("bing_6")
        self.bing_0 = QtWidgets.QRadioButton(self.bing_copyright)
        self.bing_0.setGeometry(QtCore.QRect(10, 20, 241, 16))
        self.bing_0.setObjectName("bing_0")
        self.naver_copyright = QtWidgets.QGroupBox(Dialog)
        self.naver_copyright.setGeometry(QtCore.QRect(110, 10, 250, 161))
        self.naver_copyright.setObjectName("naver_copyright")
        self.naver_0 = QtWidgets.QRadioButton(self.naver_copyright)
        self.naver_0.setGeometry(QtCore.QRect(10, 20, 241, 16))
        self.naver_0.setObjectName("naver_0")
        self.naver_1 = QtWidgets.QRadioButton(self.naver_copyright)
        self.naver_1.setGeometry(QtCore.QRect(10, 40, 241, 16))
        self.naver_1.setObjectName("naver_1")
        self.naver_2 = QtWidgets.QRadioButton(self.naver_copyright)
        self.naver_2.setGeometry(QtCore.QRect(10, 60, 241, 16))
        self.naver_2.setObjectName("naver_2")
        self.naver_4 = QtWidgets.QRadioButton(self.naver_copyright)
        self.naver_4.setGeometry(QtCore.QRect(10, 80, 241, 16))
        self.naver_4.setObjectName("naver_4")
        self.result = QtWidgets.QLabel(Dialog)
        self.result.setGeometry(QtCore.QRect(10, 350, 351, 51))
        self.result.setText("")
        self.result.setWordWrap(True)
        self.result.setObjectName("result")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.download.setText(_translate("Dialog", "사진 저장"))
        self.engine_box.setTitle(_translate("Dialog", "검색 엔진"))
        self.google.setText(_translate("Dialog", "Google"))
        self.naver.setText(_translate("Dialog", "Naver"))
        self.bing.setText(_translate("Dialog", "Bing"))
        self.google_copyright.setTitle(_translate("Dialog", "Google 이미지 사용권"))
        self.google_0.setText(_translate("Dialog", "라이선스로 필터링 안함"))
        self.google_1.setText(_translate("Dialog", "수정 후 재사용 가능"))
        self.google_2.setText(_translate("Dialog", "재사용 가능"))
        self.google_3.setText(_translate("Dialog", "수정 후 비상업적 용도로 재사용 가능"))
        self.google_4.setText(_translate("Dialog", "비상업적 용도로 재사용 가능"))
        self.select_folder.setText(_translate("Dialog", "저장 경로"))
        self.select_driver.setText(_translate("Dialog", "driver 경로"))
        self.bing_copyright.setTitle(_translate("Dialog", "Bing 라이선스"))
        self.bing_1.setText(_translate("Dialog", "모든 Creative Commons"))
        self.bing_2.setText(_translate("Dialog", "공용 도메인"))
        self.bing_3.setText(_translate("Dialog", "무료 공유 및 사용"))
        self.bing_4.setText(_translate("Dialog", "상업적으로 무료 공유 및 사용"))
        self.bing_5.setText(_translate("Dialog", "무료 수정, 공유 및 사용"))
        self.bing_6.setText(_translate("Dialog", "상업적으로 무료 수정, 공유 및 사용"))
        self.bing_0.setText(_translate("Dialog", "전체"))
        self.naver_copyright.setTitle(_translate("Dialog", "Naver CCL"))
        self.naver_0.setText(_translate("Dialog", "CCL 없음"))
        self.naver_1.setText(_translate("Dialog", "CCL 전체"))
        self.naver_2.setText(_translate("Dialog", "상업적 이용 가능"))
        self.naver_4.setText(_translate("Dialog", "원본 수정 가능"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

